stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/tested.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/preprocessing.py
      - src/model_factory.py
      - src/config_loader.py
      - config.yaml
      - data/tested.csv
    outs:
      - models/pipeline.pkl